//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVote
    {
        public int UserVoteID { get; set; }
        public string UserID { get; set; }
        public int PostID { get; set; }
        public bool Vote { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
